### PR TITLE
commands added

### PR DESCRIPTION
**Pull request by VitorDiass**
Hello ! 

I saw your requests and decided to help.

First i added a new option to the `cd` command, now the user is able to see the effect of `cd ..` . 
Then after `mkdir` command i added the `clear` command in order to let user clear their screen (Also added one more position to the array called "arr".
I guess this two commands are import for any terminal user, especially `cd ..`.
Also i tried to keep it simple and do not change the logic of the program. 

Hope i could help you ! 

Greetings

### CODE REVIEW

**Comment by sr6033** [comment]
Thank you for the addition. It would be great if people keep on adding more commands. It will be a good place for newbies. 

I specifically want to implement pipeline.
For example: ./a.out > output.txt

**Comment by VitorDiass** [comment]
I was thinking about implement a redirector command too (> or < are redirectors and | is the pipeline, i think so), anyways... I dont know how you want it to work. I mean, do you only want to explain what a it does? Or something more developed?

**Comment by sr6033** [comment]
I am sorry. I meant the redirector. ">" & "<"

**Comment by VitorDiass** [comment]
@sr6033 My point is, do you want just show the result and the why they are useful? Or do you want something more develoted? 
I will try something and you see is its fits what you want

**Comment by sr6033** [comment]
I want it to work the same way it does in a real bash terminal and show the result. I am creating an issue for it. If you are able to complete it, PR it.
Thanks :)

**Pull request merged**
