### PR TITLE
added history command

### PR DESCRIPTION
**Pull request by nvinayvarma189**
I added the history command and gave a description about it.

### CODE REVIEW

**Comment by nvinayvarma189** [comment]
Please review this PR and kindly notify me if there are changes requested

**Comment by sr6033** [comment]
The `history` command is also getting shown. I don't want that to be shown on typing `history`. Make a condition to exclude it.

**Comment by nvinayvarma189** [comment]
Ok, will change that now

**Comment by nvinayvarma189** [comment]
I excluded it from being shown . I can add it if you want it

**Comment by sr6033** [comment]
Edit your PR accordingly and let me know. I will merge it.

**Pull request merged**
